version: 0.2
phases:
  install:
    commands:
      - npm install
      # Start our application
      - node main.js > /dev/null &           
      # Download ngrok and open tunnel to our application
      - wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      - unzip ngrok-stable-linux-amd64.zip
      - chmod +x ngrok
      - ./ngrok authtoken 1RbrqLmohbIbSx0VI39d8BtXeck_2jboifHNRpeCZG2XZYRAT
      - ./ngrok http 127.0.0.1:3001 > /dev/null &
      # Download json parser for determining ngrok tunnel
      - wget https://stedolan.github.io/jq/download/linux64/jq
      - chmod +x jq        
      # Execute Ghost Inspector tests using the ngrok tunnel
      - curl "https://api.ghostinspector.com/v1/suites/5d9381217e0db75c2e2bf8b6/execute/?apiKey=9f234853a23e845b2f41601e2b694df88ebd0fcb&startUrl=$(curl 'http://127.0.0.1:4040/api/tunnels' | ./jq -r '.tunnels[1].public_url')" > ghostinspector.json
      # Exit with a fail status if any tests have failed
      - if [ $(grep -c '"passing":false' ghostinspector.json) -ne 0 ]; then exit 1; fi
  build:
    commands:


    